# Generated by Django 6.0.1 on 2026-02-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Ej påbörjad'), ('IN_PROGRESS', 'Pågående'), ('FINISHED', 'Avklarad')], default='NOT_STARTED', max_length=15)),
            ],
        ),
    ]
